config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      mount ActionCable.server => '/cable'
  namespace :admins do
    resources :admins
    resources :spaces
    resources :geres
    resources :amenities
    resources :users
    resources :chats
    resources :reservations
    resources :rooms
  end

  get "admins" => "admin#index"

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }



	devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'

      }
   root to: 'spaces#index'
   
   resources :spaces do

    resources :space_images
    resources :reservations
    resource :favorites, only: [:create, :destroy]
   end

   resources :users
   
   resources :genres
   resources :categories
   resources :facilitys
   resources :amenities
   resources :rooms do
     resources :comments
   end
   resources :space_images, only: [:destroy]
   get 'rooms/create/:id' => 'rooms#create', as: "create_room"
   post "spaces/:space_id/reservations/confirm" => "reservations#confirm" ,as:"confirm"
   post "spaces/:space_id/reservations/change" => "reservations#change" ,as:"change"
   get "spaces/:id/categoryfacility/new" => "spaces#category_facility", as: "new_category_facility"
   patch "spaces/:id/categoryfacility/new" => "spaces#create_category_facility", as: "create_category_facility"
   patch "space/:id" => "spaces#space_images_deleate", as: "space_images_deleate"
   get "genres/:genre_id/search/" => "searchs#show", as:"search"
   get "user/:id/reservations" => "reservations#user_reservations",as:"user_reservations"
   patch "space/category_facility" => "spaces#category_facility_update",as:"space_genres_amenities"
end

app/models/space.rb
class Space < ApplicationRecord
	has_many :favorites, dependent: :destroy
	has_many :reservations, dependent: :destroy
	has_many :categories, dependent: :destroy
	has_many :facilitys, dependent: :destroy
	has_many :space_images, dependent: :destroy
 	accepts_attachments_for :space_images, attachment: :image

 	validates :space_images_images, presence: true
 	# validates_attachment_content_type :space_images_images
 	validates :name, presence: true
	validates :price, presence: true
	validates :capacity, presence: true
	validates :address, presence: true
	geocoded_by :address
  	after_validation :geocode
	
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	
end

app/controllers/admins/spaces_controller.rb
class Admins::SpacesController < ApplicationController

	def index
		@spaces = Space.all
	end

	def show
		@space = Space.find(params[:id])
	end

	def destroy
		space = Space.find(params[:id])
		space.destroy
		redirect_to admins_spaces_path
	end

	# private
	# def destroy_params
	# 	params.require(:).permit(:nickname, :email, :name_family_name, :name_name, :furigana_family_name, :furigana_name_name)
		
	# end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

	def index
		@spaces = Space.all
		# @spaces_image = SpaceImage.where(image_id: @space.id)
		# @spaces.where('created_at > ?', 1.day.ago)
		# @categorys = nil
		
	end

	def show
		@space = Space.find(params[:id])
		@categories = Category.where(space_id: @space.id)
		@facilitys = Facility.where(space_id: @space.id)
		@user = User.find(@space.lender_id)
		@genres = Genre.all
		# @genres_array = []
		# 		@genres.each do |genre|
	 # 			@genres_array << [genre.name,genre.name]
	 # 		end
	 	@amenities = Amenitie.all
	 # 	@amenities_array = []
	 # 			@amenities.each do |amenitie|
	 # 			@amenities_array = [amenitie.name,amenitie.name]
	 # 		end
	 		# binding.pry
	end

	def new
		@space = Space.new
		@space.space_images.build
	end

	def update
		@space = Space.find(params[:id])
		@space.update(params_update)
		redirect_to spaces_path



	end

	def space_images_deleate
		images = params["space"]["image_id"]
		images.delete("0")

		space = Space.find(params[:id])
		space_images = SpaceImage.where(space_id: space.id)

		 images.each do |image|
		 	select_image = space_images.find(image.to_i)
		 	select_image.delete
		 end
		redirect_to space_path(space)

	end



	def create
		@space = Space.new(new_space)
		@space.lender_id = current_user.id
		@images = @space.space_images_images.count
		if @images < 5
			if @space.save
			 redirect_to new_category_facility_path(@space)
			else
			  render "new"
			end
		else
			render "new", notice: '画像の投稿は５枚までにしてください。'
		end

	end

	def destroy
		space = Space.find(params[:id])
		space.destroy
		redirect_to spaces_path
	end

	def category_facility
		@space = Space.find(params[:id])
		@space.categories.build
		@genres = Genre.all

		@space.facilitys.build
		@amenities = Amenitie.all
	end
	def category_facility_update
		
	end



	def create_category_facility
		params["space"]["category"]["genre_id"].delete("0")
		params["space"]["category"]["genre_id"].each do |genre_number|
		
			category = Category.new(genre_id: genre_number.to_i,space_id: params[:id])
			category.save
		end
		params["space"]["facility"]["amenitie_id"].delete("0")
		params["space"]["facility"]["amenitie_id"].each do |amenitie_number|
			facility = Facility.new(amenitie_id: amenitie_number.to_i,space_id: params[:id])
			facility.save
		end
		redirect_to spaces_path

	end





	private

		def new_space
			params.require(:space).permit(:name, :description, :address, :latitude, :longitude, :capacity, :price, space_images_images: [])
		end

		def params_update
			params.require(:space).permit(:id, :image, :name, :description, :address, :capacity, :price)
		end

		
		# def index_spaces
		# 	params.require(:space).permit(:id, :image, :name, :description, :addres, :capacity, :price)
		# end


end

app/helpers/admins/spaces_helper.rb
module Admins::SpacesHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_category_facility.html.erb
<h2>genre.amenitieの編集</h2>


<% genres.each do |genre| %>
  <%= genre.name %>
<% end %>


<% amenities.each do |amenitie| %>
  <%= amenitie.name %>
<% end %>

app/views/spaces/category_facility.html.erb
<div class="container-fluid">
  <div class="row sampleRow">
	<div class="col-md-1">
	</div>
	  <div class="col-md-10">
		<div class="genres_box">
		 <p>ジャンルは３つまで登録可能です</p>
		  <%= nested_form_for (@space), url:create_category_facility_path(id: @space.id) do |f| %>
		    <%= f.fields_for :category do |tf| %>
		    <%= tf.label "ジャンルを選択してください"%><br>
			  <% @genres.each do |genre| %>
			  <%= tf.check_box :genre_id, {class: 'checkbox',multiple: true}, genre.id %>
			  <%= genre.name %>
		    <% end %>
		  <% end %>
		</div>

	<%= f.fields_for :facility do |tf| %>
	<%= tf.label "アメニティを選択してください" %><br>
		<% @amenities.each do |amenitie| %>
    	<%= tf.check_box :amenitie_id, {multiple: true}, amenitie.id %>
		<%= amenitie.name %>
  		<% end %>
	<% end %><br>
  <%= f.submit"スペースを登録する"%>
<% end %>
</div>
	<div class="col-md-1">
	</div>
  </div>
</div>
<!-- <input type="checkbox" name="" id="checkbox"> -->
<script>
	// チェックボックスの制限
$(function(){
 	$('.checkbox').click(function(){
		var clicked_length = $('.checkbox:checked').length;
		// alert(clicked_length);
		if (clicked_length >= 3){
			$('.checkbox:not(:checked)').attr('disabled', 'disabled');
    	}else {
      		$('.checkbox:not(:checked)').removeAttr('disabled');
    	}
	});
 });
</script>

app/views/spaces/index.html.erb
<%= stylesheet_link_tag 'front/space'%>

<div class="container-fluid">
  <div class="row sampleRow">
    <div class="col-md-1">
    </div>
<!-- タブの表示してるよ -->
    <div class="col-md-10">
      <div class="tab-box">
		<li>
            <%= link_to "ALL",spaces_path, class: "genre"%>
		</li>
		<li>
			<%= link_to "PARTY",search_path(1), remote: true , class: "genre"%>
		</li>
		<li>
			<%= link_to "セミナー",search_path(2), remote: true , class: "genre"%>
		</li>
		<li>
			<%= link_to "合コン",search_path(3), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "スポーツ",search_path(4), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "会議",search_path(5), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "イベント",search_path(6), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "オフィス",search_path(7), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "アウトドア",search_path(8), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "BBQ",search_path(9), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "ロケ撮影",search_path(10), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "写真撮影",search_path(11), remote:true , class: "genre"%>
		</li>
		<li>
			<%= link_to "民泊",search_path(12), remote:true , class: "genre"%>
		</li>
		 <li>
			<%= link_to "展示会場",search_path(13), remote:true , class: "genre"%>
		</li>
      </div>

      <div class="spaces_box index search" id='show'>
        <% @spaces.each do |space| %>
            <div class="space_mini_box">
              <div class="theTarget single-item">
                  <% space.space_images.each do |space_image| %>
                  <div>
                    <p class="price index">¥ <%= space.price %>/1h</p>
                    <%= attachment_image_tag space_image, :image,class: "space_image index" %>
                  </div>
                  <% end %>
              </div>
              <div class="space_text index">
                <p><%= link_to space.name.truncate(40,omission: '...') ,space_path(space.id) %></p>
                <p class="glyphicon glyphicon-flag addres index"><%= space.address %></p>
                <p class="glyphicon glyphicon-user capacity index">~<%= space.capacity %>人</p>
              </div>
            </div>
        <% end %>
      </div>


    </div>

    <div class="col-md-1">
    </div>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="container-fluid">
  <div class="row sampleRow">
	<div class="col-md-1">
	</div>
	  <div class="col-md-10">

		<%= form_for(@space) do |f| %>
		<!-- 複数できるように -->
		
		<div class="row sampleRow">
			<div class="col-md-12">
				<div class="new-space-form-box">

					<% if @space.errors.any? %>
				  <h2><%= pluralize(@space.errors.count, "error") %> prohibited this map from being saved:</h2>
				  <% @space.errors.full_messages.each do |message| %>
				  <%= message %>
				  <% end %>
				  <% end %>
				  <%= f.label "掲載できる写真は５枚までです。" %>
				 <%= f.attachment_field :space_images_images, multiple: true%>
				<% if flash[:notice] %>
	    		<%= flash[:notice] %>
					<% end %>

					<div class="new-space-name-form">
					  <%= f.label "NAME",class: "new-space-label"%>
						<div clss="space-name-form">
					  		<%= f.text_field :name, class: "space-name-form"%>
						</div>
					</div>

					<div class="new-space-description-form">
					  <%= f.label "DESCRIPTION",class: "new-space-label"%>
					  <div clss="space-description-form">
					  		<%= f.text_area :description, class: "space-discription-form"%>
						</div>
					</div>


				  	<div class="new-space-addres-form">
				      <%= f.label "ADDRES",class: "new-space-label addres" %>
				      <div class="space-addres-form">
				  	  	<%= f.text_field :address, class: "space-addres-form"%>
				      </div>
				  	</div>	

				  	<div class="row sampleRow">

						<div class="col-md-4">
				  			<div class="new-space-capacity-form">
					  			<%= f.label "CAPACITY",class: "new-space-label capacity" %>
					  			<div class="space-capacity-form">
					  	  		<%= f.number_field :capacity, class: "space-capacity-form" %>
					    		</div>
				  			</div>
					    </div>
					    <div class="col-md-4">
						  	<div class="new-space-price-form">
							  	<%= f.label "PRICE/1h",class: "new-space-label price" %>
							  	<div class="space-capacity-form">
							  	  <%= f.text_field :price, class: "space-price-form" %>
							  	</div>
						  	</div>
					    </div>

					    <div class="col-md-4">
					    	<div class="new-space-registration-btn">
				  				<%= f.submit "REGISTRATION", class: "space-registration-btn" %>
					    	</div>
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
		<% end %>
	  </div>
	<div class="col-md-1">
	</div>
  </div>
</div>

app/views/spaces/show.html.erb
<%= stylesheet_link_tag 'front/space'%>
<div class="container-fluid show">
  <div class="row sampleRow">
    <div class="col-md-1">
    </div>
    <div class="col-md-10 space_show_edit">

<% if user_signed_in? && current_user.id == @space.lender_id %>
<!--  loginかつ自分の -->

    <%= form_for (@space),url:space_images_deleate_path do |f| %>
      <% @space.space_images.each do |image| %>
        <%= attachment_image_tag image, :image,fallback: "no_image.jpg",class: "show_image",id: "space_image" %>
        <%= f.check_box :image_id, {multiple: true}, image.id %>
      <% end %>
      <%=f.submit "削除"%>
    <% end %>


    <div class="container-fluid">
      <div class="row sampleRow">
        <%= form_for @space do |f| %>
          <div class="col-md-8">

            <div class="name_box edit">
              <p class="name edit"><%= f.text_field :name,class: "name_form edit" %></p>
            </div>

            <div class="space_text edit">
              <p class="glyphicon glyphicon-flag text"><%= f.text_field :address,class: "addres_form edit"%></p>
              <p class="glyphicon glyphicon-user text">〜<%= f.number_field :capacity,class: "capacity_form edit" %>人</p>
              <p class="glyphicon glyphicon-tag text">
                <% @space.categories.each do |category| %>
                  <%= category.genre.name %>
                <% end %>
              </p>
            </div>

            <div class="amenities_box show">
              <p class="glyphicon glyphicon-link">アメニティー</p>
            <div>

            <% @space.facilitys.each do |facility| %>
              <p class="glyphicon glyphicon-ok"><%= facility.amenitie.name %></p>
            <% end %>

            <button type="button" id="open">genre.amenitieの編集</button>
            <div id="modal" class="hidden">
                <%= render 'spaces/category_facility',genres: @genres,categories: @categories,acilitys: @facilitys,amenities: @amenities %>
                  <button type="button" id="close">閉じる</button>
              </div>
              <div id="mask" class="hidden"></div>
            </div>


            <div class="description_box edit">
                 <p class="description edit"><%= f.text_area :description,class: "description_form edit"%></p>
            </div>

            <div class="price_box edit">
                <p class="price edit">¥<%= f.text_field :price,class: "price_form edit"%>/1h</p>
              </div>

          </div>
        </div>

          <div class="col-md-4">
            <%= f.submit "編集内容を保存する",class: "space_button edit"%>
            <button type="button" class="space_button edit">
              <%= link_to'このスペースを削除する',space_path(@space.id), method: :delete, "data-confirm" => "削除しますか？" %>
            </button>
            <button type="button" class="space_button edit">
              <%= link_to "ユーザー情報",user_path(current_user.id) %>
            </button>
          </div>
        <% end %>



        <script>
          $(function() {
              var open = document.getElementById('open');
  var close = document.getElementById('close');
  var modal = document.getElementById('modal');
  var mask = document.getElementById('mask');
    ('#open').click
    open.addEventListener('click', function() {
    modal.className = '';
    mask.className = '';
  });

$(function(){
    $('#open').click(function(){
        $('#modal').removeClass('hidden');
        $('#mask').removeClass('hidden');
    });
    $('#close').click(function(){
        $('#modal').addClass('hidden');
        $('#mask').addClass('hidden');
    });
    });
});
        </script>



<% elsif user_signed_in? %>
    <!-- loginかつ他の -->


    <div class="container show">
      <div class="theTarget single-item">
        <% @space.space_images.each do |image| %>
        <div><%= attachment_image_tag image, :image,fallback: "images/no_image.jpg",class: "image show",id: "space_image"%></div>
        <% end %>
      </div>
    </div>


    <div class="container-fluid">
      <div class="row sampleRow">
        <div class="col-md-8">
              <div class="name_box show">
                  <p class="name show"><%= @space.name %></p>
              </div>

              <div class="space_text show">
                <p class="glyphicon glyphicon-flag text"><%= @space.address %></p>
                <p class="glyphicon glyphicon-user text">〜<%=@space.capacity %>人</p>
                <p class="glyphicon glyphicon-tag text">
                  <% @categories.each do |category| %>
                    <%= category.genre.name %>
                  <% end %>
                </p>
              </div>

              <div class="amenities_box show">
                <p class="glyphicon glyphicon-link">アメニティー</p>
                <div>
                  <% @facilitys.each do |facility| %>
                  <p class="glyphicon glyphicon-ok"><%= facility.amenitie.name %></p>
                  <% end %>
                </div>
              </div>

              <div class="description_box show">
                 <p class="description show"><%= simple_format(@space.description) %></p>
              </div>
        </div>

        <div class="col-md-4">
          <div class="sideber show">
            <div class="like_box show">
              <% if @space.favorited_by?(current_user) %>
                <li>
                  <%= link_to space_favorites_path(@space), method: :delete do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= @space.favorites.count %> お気に入り
                    <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to space_favorites_path(@space), method: :post do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                    <%= @space.favorites.count %> お気に入り
                  <% end %>
                </li>
              <% end %>
            </div>

            <div class="price_reserve_box show">
              <div class="price_box show">
                <p class="price show">¥<%= @space.price %>/1h</p>
              </div>
              <div class="reservation_box show">
                <p class="reservation show"><%= link_to "予約画面へ",new_space_reservation_path(@space) %></p>
              </div>
            </div>
            <div class="user_box show">
              <%= attachment_image_tag @user, :profile_image,fallback: "images/no_image.jpg",class: "profile-image show" %>
              <%= link_to "#{@user.nickname}さん", user_path(@space.lender_id) %>
            </div>
          </div>
        </div>

      </div>
    </div>
      <!-- グーグルマップ -->
     <!--  -->

  <% else %>
    <!-- loginしてない -->
    <div class="container show">
      <div class="theTarget single-item">
          <% @space.space_images.each do |image| %>
            <div><%= attachment_image_tag image, :image,fallback: "images/no_image.jpg",class: "image show",id: "space_image"%></div>
          <% end %>
          </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row sampleRow">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
              <div class="name_box show">
                  <p class="name show"><%= @space.name %></p>
              </div>

              <div class="space_text show">
                <p class="glyphicon glyphicon-flag text"><%= @space.address %></p>
                <p class="glyphicon glyphicon-user text">〜<%=@space.capacity %>人</p>
                <p class="glyphicon glyphicon-tag text">
                  <% @categories.each do |category| %>
                    <%= category.genre.name %>
                  <% end %>
                </p>
              </div>

              <div class="amenities_box show">
                <p class="glyphicon glyphicon-link">アメニティー</p>
                <div>
                  <% @facilitys.each do |facility| %>
                  <p class="glyphicon glyphicon-ok"><%= facility.amenitie.name %></p>
                  <% end %>
                </div>
              </div>

              <div class="description_box show">
                 <p class="description show"><%= simple_format(@space.description) %></p>
              </div>
          </div>
        <div class="col-md-1">
        </div>
      </div>
    </div>


    <% end %>
  </div>

    <div class="col-md-1">
    </div>

</div>
</div>

app/views/spaces/show2.js.erb
$(function(){

    $(document).on("ajax:success", ".genre", function(e) {
         $(this).slideDown(800)
         $('#show').html('<%= j(render "searchs/show",categorys: @categorys) %>');
    });
});