config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      mount ActionCable.server => '/cable'
  namespace :admins do
    resources :admins
    resources :spaces
    resources :geres
    resources :amenities
    resources :users
    resources :chats
    resources :reservations
    resources :rooms
  end

  get "admins" => "admin#index"

  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }



	devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'

      }
   root to: 'spaces#index'
   
   resources :spaces do

    resources :space_images
    resources :reservations
    resource :favorites, only: [:create, :destroy]
   end

   resources :users
   
   resources :genres
   resources :categories
   resources :facilitys
   resources :amenities
   resources :rooms do
     resources :comments
   end
   resources :space_images, only: [:destroy]
   get 'rooms/create/:id' => 'rooms#create', as: "create_room"
   post "spaces/:space_id/reservations/confirm" => "reservations#confirm" ,as:"confirm"
   post "spaces/:space_id/reservations/change" => "reservations#change" ,as:"change"
   get "spaces/:id/categoryfacility/new" => "spaces#category_facility", as: "new_category_facility"
   patch "spaces/:id/categoryfacility/new" => "spaces#create_category_facility", as: "create_category_facility"
   patch "space/:id" => "spaces#space_images_deleate", as: "space_images_deleate"
   get "genres/:genre_id/search/" => "searchs#show", as:"search"
   get "user/:id/reservations" => "reservations#user_reservations",as:"user_reservations"
   patch "space/category_facility" => "spaces#category_facility_update",as:"space_genres_amenities"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/amenitie.rb
class Amenitie < ApplicationRecord
	has_many :facilitys, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :space 
	belongs_to :genre
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :room
	belongs_to :user
end

app/models/facility.rb
class Facility < ApplicationRecord
	belongs_to :space
	belongs_to :amenitie
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :space
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :categories
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :space
	belongs_to :user
	
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	

	


end

app/models/room_user.rb
class RoomUser < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/space.rb
class Space < ApplicationRecord
	has_many :favorites, dependent: :destroy
	has_many :reservations, dependent: :destroy
	has_many :categories, dependent: :destroy
	has_many :facilitys, dependent: :destroy
	has_many :space_images, dependent: :destroy
 	accepts_attachments_for :space_images, attachment: :image

 	validates :space_images_images, presence: true
 	# validates_attachment_content_type :space_images_images
 	validates :name, presence: true
	validates :price, presence: true
	validates :capacity, presence: true
	validates :address, presence: true
	geocoded_by :address
  	after_validation :geocode
	
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
	
end

app/models/space_image.rb
class SpaceImage < ApplicationRecord
	belongs_to :space
	attachment :image
end

app/models/time_count.rb
class TimeCount < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  	attachment :profile_image
  	has_many :favorites, dependent: :destroy
  	has_many :reservations, dependent: :destroy
  	has_many :comments, dependent: :destroy
  	has_many :room_users, dependent: :destroy



  	validates :nickname, presence: true
	validates :email, presence: true
	validates :name_family_name, presence: true
	validates :name_name, presence: true
	validates :furigane_family_name, presence: true
	validates :fuigana_name_name, presence: true
	validates :furigana_family_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  	validates :furigana_name, presence: true, format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

  	


    def self.search(search)
	    if search
	      User.where(['email LIKE ?', "%#{search}%"])
	    else
	      User.all
	    end
  	end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
	def index
		@spaces = Space.where(category_id: params[:genre_id])

	end
	def show
		@categorys = Category.where(genre_id: params[:genre_id])
		p @categorys
		# space= Space.where(id: @categorys.space_id)
		respond_to do |format|
			format.html {render :partial => "show", :locals => { :categorys => @categorys}}
			format.js
		end
	end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searchs/_show.html.erb
<div class="container-fluid">
  <% categorys.each do |category| %>
      <div class="space_mini_box">
        <div class="theTarget single-item">
            <% category.space.space_images.each do |space_image| %>
            <div>
             <p class="price index">¥<%= category.space.price %>/1h</p>
              <%= attachment_image_tag space_image, :image,fallback: "no_image.jpg",class: "space_image index"%>
            </div>
            <% end %>
        </div>
        <div class="space_text index">
          <p><%= link_to category.space.name.truncate(40,omission: '...') ,space_path(category.space.id) %></p>
          <p class="glyphicon glyphicon-flag addres index"><%= category.space.address %></p>
          <p class="glyphicon glyphicon-user capacity index">~<%= category.space.capacity %>人</p>
        </div>
      </div>
  <% end %>
</div>

app/views/searchs/index.html.erb
<h1>検索結果表示画面</h1>

<% @sapces.each do |space| %>
<%= space.name %>
<% end %>

app/views/searchs/show.js.erb
$('#show').html("<%= j(render 'searchs/show',categorys: @categorys) %>");
console.log('<%= @categorys %>');


$("document").ready(function() {
    $(".theTarget").skippr();
});
// オプションを指定してSkipprの実行
$(".theTarget").skippr({
    // スライドショーの変化 ("fade" or "slide")
    transition : 'slide',
    // 変化に係る時間(ミリ秒)
    speed : 1000,
    // easingの種類
    easing : 'easeOutQuart',
    // ナビゲーションの形("block" or "bubble")
    navType : 'block',
    // 子要素の種類("div" or "img")
    childrenElementType : 'div',
    // ナビゲーション矢印の表示(trueで表示)
    arrows : true,
    // スライドショーの自動再生(falseで自動再生なし)
    autoPlay : false,
    // 自動再生時のスライド切替間隔(ミリ秒)
    autoPlayDuration : 5000,
    // キーボードの矢印キーによるスライド送りの設定(trueで有効)
    keyboardOnAlways : true,
    // 一枚目のスライド表示時に戻る矢印を表示するかどうか(falseで非表示)
    hidePrevious : false
})